apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: x7cl8gh3k-java-quarkus
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-2d7e9eb215.2y37.p3.openshiftapps.com/rhtap/rhtap-qe:48cea2f26b22c59c04544dc8b40846d3e8abab1f@sha256:1a689dd6fb6481a1d0c0288ea2e96cf129bfb0e5e18402c8f0088c617dd2763d
        name: container-image  
